version: '3.1'

services:
  php:
    container_name: 'server_${serverName}'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    build: 
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - ${port}:80
    volumes:
      - ${pathApp}:/var/www/html/
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "${passwordDB}*"
      ACCEPT_EULA: "Y"